### ISSUE TITLE
Common Malformed File Exception

### ISSUE THREAD

**Issue by CiaranOMara** [BioJulia/BioGenerics.jl#8]
@BenJWard and @jakobnissen, would it be useful to set up a common malformed file exception for the likes of XAM, FASTX, and the other Automa based parsers?

Below is an example to start a conversation.
```julia
struct MalformedFileError <: Exception
    state::BioGenerics.Automa.State
end

Base.showerror(io::IO, e::MalformedFileError) = print(io, "Malformed file: ", e.state)

throw(MalformedFileError(reader.state))
```

**Comment by jakobnissen** [comment]
Only seeing this now.
Yeah - but I think it should be in Automa, actually. I've added an exception in https://github.com/BioJulia/Automa.jl/pull/64 that looks like this:

```
ERROR: Error during FSM execution at buffer position 33.
Last 33 bytes were:

"\n>good_record\nATAGA\n>bad_record\n>"

Observed input: '>' at state 4. Outgoing edges:
 * [*\-A-Za-z]/mark
 * [\t\v ]
 * '\n'/countline
 * '\r'
 * EOF/record

Input is not in any outgoing edge, and machine therefore errored.
```

I've begun work on making this error the default in Automa, or making it very easy for downstream packages to opt-in to the error.

**Comment by CiaranOMara** [comment]
It looks like the improved Automa error will be sufficient. I think the issue can be reopened if there is a need to extend the new FSM error or distinguish a file format error.
